CREATE TABLE users (
    name varchar(20) PRIMARY KEY
);

CREATE TABLE characterSheets (
	id SERIAL PRIMARY KEY,
	player varchar(50) REFERENCES users(name),
	char_name varchar(50) UNIQUE not null,
	gender varchar(20),
	age int,
	background varchar(50),
	bad_skill1 varchar(20),
	bad_skill2 varchar(20),
	bad_skill3 varchar(20),
	good_skill varchar(20),
	great_skill varchar(20),
	height float,
	weight float,
	description text,
	char_level int,
	injuries int DEFAULT 0,
	hp int DEFAULT 10,
	atk int DEFAULT 5,
	def int DEFAULT 5,
	spatk int DEFAULT 5,
	spdef int DEFAULT 5,
	speed int DEFAULT 5,
	abilities text,
	moves text,
	classes int DEFAULT 0,
	head_equipment text,
	body_equipment text,
	main_hand text,
	off_hand text,
	feet_equipment text,
	accessory text,
	items text,
	money int,
    notes text
);

CREATE TABLE pokemonSheets (
	id SERIAL PRIMARY KEY,
	player varchar(50) REFERENCES users(name),
	pokemon_name varchar(50),
	species text not null,
	type1 varchar(10) not null,
	type2 varchar(10),
	poke_level int,
	held_item text,
	loyalty int,
	gender varchar(20),
	nature varchar(20),
	ability1 text not null,
	ability2 text,
	ability3 text,
	height float,
	weight_class int,
    overland int,
    swim int,
    jump_long int,
    jump_high int,
    power int,
    fly int DEFAULT 0,
    levitate int DEFAULT 0,
	capabilities text,
	skill_athl int,
	skill_athl_bonus int DEFAULT 0,
	skill_acro int,
	skill_acro_bonus int DEFAULT 0,
	skill_combat int,
	skill_combat_bonus int DEFAULT 0,
	skill_stealth int,
	skill_stealth_bonus int DEFAULT 0,
	skill_percep int,
	skill_percep_bonus int DEFAULT 0,
	skill_focus int,
	skill_focus_bonus int DEFAULT 0,
	other_skills text,
	hp int,
	atk int,
	def int,
	spatk int,
	spdef int,
	speed int,
	injuries int DEFAULT 0,
	move1 text,
	move2 text,
	move3 text,
	move4 text,
	move5 text,
	move6 text,
	move7 text,
	move8 text,
	move9 text,
	tutor_points int,
	tutor_items text,
	inheritance_moves text,
	vitamins text,
	notes text
);